
import styles from '../styles/Home.module.css'
import Head from 'next/head'


export default function Home() {
  
  return (

    
    <div className={styles.container}>
        <Head>
        <title> Almesrah </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      

    
      
    </div>
  )
}

