
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  
  return (

    
    <div className={styles.container}>
        <Head>
        <title> Almesrah </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>

       <Image
        src="/pic1 (1).jpeg"
        alt="Picture of the author"
        width={400}
        height={400}
      />
       <Image
        src="/pic1 (2).jpeg"
        alt="Picture of the author"
        width={400}
        height={400}
      />

    
      
    </div>
  )
}

