import Link from "next/link"
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (

    
    
    <div className={styles.container}>
        <Head>
        <title> Almesrah </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      

    {/*   <main className={styles.main}>
        <h2 className={styles.title}>
        Almesrah
        </h2>

        <div className={styles.grid}>
          <Link href="/" >
            <div className={styles.card}>
            <h2>Home &rarr;</h2>
            </div>
          </Link>

          <Link href="/about" >
          <div className={styles.card}>
            <h2>About &rarr;</h2>
            </div>
          </Link>

          <Link
            href="/contact"
            
          >
            <div className={styles.card}>
            <h2>Contact &rarr;</h2>
            </div>
          </Link>

        </div>
      </main> */}
      
    </div>
  )
}